### ISSUE TITLE
Run program

### ISSUE THREAD

**Issue by DjarallahBrahim** [rsommerard/ftp-server-java#1]
How we can Run it ?

**Comment by rouvoy** [comment]
`java -jar ftp-server-java.jar` cc @m3ftah

**Comment by m3ftah** [comment]
+1

**Comment by DjarallahBrahim** [comment]
@rouvoy 
actually i almost finish my server, what i want to do is making a folder for each user , 
with that every user has their own folder in the server and he can not get out from his folder , he can just use the sub folders.
is that the right method to protect users folders ? 
or i should let all the users use the same folder (Root) ?
Thank you

**Comment by DjarallahBrahim** [comment]
@rouvoy 
actually i'm working on my server, what i want to do is making a folder for each user , 
with that every user has their own folder in the server and he can not get out from his folder , he can just use the sub folders.
is that the right method to protect users folders ? 
or i should let all the users use the same folder (Root) ?
Thank you

**Comment by DjarallahBrahim** [comment]
@rouvoy 
actually i'm working on my server, what i want to do is making a folder for each user , 
with that every user has their own folder in the server and he can not get out from his folder , he can just use the sub folders.
is that the right method to protect users folders ? 
or i should let all the users use the same folder (Root) ?
Thank you

**Comment by rouvoy** [comment]
GitHub is not the best place to ask these questions, I would recommend you to discuss it during the lab session.

Best,
R. Rouvoy
